INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (1, 'Laptop', b'1', 'laptop.jpg', 'Laptop', NULL);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (2, 'Linh-kiện', b'1', 'linh-kien.jpg', 'Linh kiện', NULL);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (3, 'Màn-hình', b'1', 'man-hinh.jpg', 'Màn hình', NULL);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (4, 'Bàn-phím', b'1', 'ban-phim.jpg', 'Bàn phím', NULL);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (5, 'Tai-nghe', b'1', 'tai-nghe.jpg', 'Tai nghe', NULL);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (6, 'Chuột-bàn-phím', b'1', 'chuot-ban-phim.jpg', 'Chuột bàn phím', NULL);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (7, 'Phụ-kiện', b'1', 'phu-kien.jpg', 'Phụ kiện', NULL);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (8, 'Ghế-gaming', b'1', 'ghe-gaming.jpg', 'Ghế gaming', NULL);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (9, 'Camera', b'1', 'camera.jpg', 'Camera', NULL);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (10, 'Điện-thoại', b'1', 'cellphone.jpg', 'Điện thoại', NULL);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (11, 'Máy-ảnh', b'1', 'may-anh.jpg', 'Máy ảnh', NULL);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (12, 'Laptop-theo-thương-hiệu', b'1', NULL, 'Laptop theo thương hiệu', 1);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (13, 'Laptop-theo-cấu-hình', b'1', NULL, 'Laptop theo cấu hình', 1);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (14, 'Laptop-theo-giá', b'1', NULL, 'Laptop theo giá', 1);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (15, 'CPU', b'1', NULL, 'CPU', 2);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (16, 'Ổ-cứng', b'1', NULL, 'Ổ cứng', 2);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (17, 'Ram', b'1', NULL, 'Ram', 2);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (18, 'Màn-hình-theo-thương-hiệu', b'1', NULL, 'Màn hình theo thương hiệu', 3);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (19, 'Màn-hình-theo-độ-phân-giải', b'1', NULL, 'Màn hình theo độ phân giải', 3);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (20, 'Màn-hình-theo-giá', b'1', NULL, 'Màn hình theo giá', 3);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (21, 'Bàn-phím-có-dây', b'1', NULL, 'Bàn phím có dây', 4);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (22, 'Bàn-phím-không-dây', b'1', NULL, 'Bàn phím không dây', 4);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (23, 'Bàn-phím-theo-thương-hiệu', b'1', NULL, 'Bàn phím theo thương hiệu', 4);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (24, 'Chuột-theo-thương-hiệu', b'1', NULL, 'Chuột theo thương hiệu', 6);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (25, 'Chuột-không-dây', b'1', NULL, 'Chuột không dây', 6);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (26, 'Chuột-có-dây', b'1', NULL, 'Chuột có dây', 6);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (27, 'Tai-nghe-theo-thương-hiệu', b'1', NULL, 'Tai nghe theo thương hiệu', 5);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (28, 'Tai-nghe-có-dây', b'1', NULL, 'Tai nghe có dây', 5);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (29, 'Tai-nghe-bluetooth', b'1', NULL, 'Tai nghe bluetooth', 5);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (30, 'Cáp-sạc', b'1', NULL, 'Cáp sạc', 7);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (31, 'USB', b'1', NULL, 'USB', 7);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (32, 'Microphone', b'1', NULL, 'Microphone', 7);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (33, 'Ghế-gaming-theo-thương-hiệu', b'1', NULL, 'Ghế gaming theo thương hiệu', 8);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (34, 'Ghế-gaming-theo-giá', b'1', NULL, 'Ghế gaming theo giá', 8);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (35, 'Camera-theo-thương-hiệu', b'1', NULL, 'Camera theo thương hiệu', 9);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (36, 'Camera-theo-giá', b'1', NULL, 'Camera theo giá', 9);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (37, 'Điện-thoại-theo-thương-hiệu', b'1', NULL, 'Điện thoại theo thương hiệu', 10);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (38, 'Điện-thoại-theo-giá', b'1', NULL, 'Điện thoại theo giá', 10);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (39, 'Máy-ảnh-theo-thương-hiệu', b'1', NULL, 'Máy ảnh theo thương hiệu', 11);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (40, 'Máy-ảnh-theo-giá', b'1', NULL, 'Máy ảnh theo giá', 11);
INSERT INTO `categories` (`id`, `alias`, `enabled`, `image_path`, `name`, `parent_id`) VALUES (41, 'Vga', b'1', NULL, 'Vga', 2);
