INSERT INTO `users` (`id`, `first_name`, `last_name`, `phone_number`, `image_path`, `email`, `password`, `enabled`) VALUES (1, 'admin', '', '0123456789', NULL, 'admin@gmail.com', '$2a$10$ayX0VS4PHrLrZgEkW39lLeBdiDXd/6sLmpBOSHb1ZNVOoSC82Fffm', b'1');
INSERT INTO `users` (`id`, `first_name`, `last_name`, `phone_number`, `image_path`, `email`, `password`, `enabled`) VALUES (2, 'Thông', 'Hoàng Phạm', '0766821606', 'messi.jpg', 'thong@gmail.com', '$2a$10$y9wUF.X0frSsaUi7hYjD2.GVHq5UXE3be5g12xnURb1m/8eTfXdmS', b'1');
INSERT INTO `users` (`id`, `first_name`, `last_name`, `phone_number`, `image_path`, `email`, `password`, `enabled`) VALUES (3, 'Mẫn', 'Trần minh', '0766821606', NULL, 'man@gmail.com', '$2a$10$ulwOrcCup.2ArqBVQW.K0eD2IlgnQsMbOqcoZsrLrxLBn/fXKeYT2', b'1');
INSERT INTO `users` (`id`, `first_name`, `last_name`, `phone_number`, `image_path`, `email`, `password`, `enabled`) VALUES (4, 'vinh', 'nguyễn thái', '0123456789', NULL, 'vinh@gmail.com', '$2a$10$v87hoEWqR/e8wp0/iSu3veWoAdL3btACgeknEiFrgGzSdlSUxofTG', b'1');
INSERT INTO `users` (`id`, `first_name`, `last_name`, `phone_number`, `image_path`, `email`, `password`, `enabled`) VALUES (5, 'vinh', 'nguyễn hoàng', '0123456789', NULL, 'hoangvinh@gmail.com', '$2a$10$LZj5Dpu3rYPrVqAK6SUrk./nzh5JsePBpdFwQkTMWgf7BKA4EXiEK', b'1');
INSERT INTO `users` (`id`, `first_name`, `last_name`, `phone_number`, `image_path`, `email`, `password`, `enabled`) VALUES (6, 'long', 'trần đình', '0123456789', NULL, 'long@gmail.com', '$2a$10$AFDF5YdW/Xkzazy3PPHwyuRJVubZUWJ9o8WuOd1YIsSqPpaGceyqy', b'0');
INSERT INTO `users` (`id`, `first_name`, `last_name`, `phone_number`, `image_path`, `email`, `password`, `enabled`) VALUES (7, 'Quân', 'Nguyễn Hoàng', '0123456789', NULL, 'quan@gmail.com', '$2a$10$CLrgc5x8zwv7s2JqhYReCO3R4ZDCg11nGAKkK0YPWh9xqKP4.YPWq', b'1');
INSERT INTO `users` (`id`, `first_name`, `last_name`, `phone_number`, `image_path`, `email`, `password`, `enabled`) VALUES (8, 'nam', 'hoàng hoai', '0123456789', NULL, 'nam@gmail.com', '$2a$10$XJg3eK/XFKvh76zTiNdPZe52kO2ETQo0p64JNXF2nRXrEc9XU.nF.', b'1');
INSERT INTO `users` (`id`, `first_name`, `last_name`, `phone_number`, `image_path`, `email`, `password`, `enabled`) VALUES (9, 'kiệt', 'tạ anh', '0123456789', NULL, 'kiet@gmail.com', '$2a$10$Pbh7jlFAqOxTiApstPFGjunUHJ2f2LcyiZz.jQ2g2EO1EJNHy4NT.', b'1');
